### ISSUE TITLE
Deploy fix for master memory loss on crash

### ISSUE THREAD

**Issue by vsinghkpcc** [SCPR/deprecated-StreamMachine#1]
If the master crashes, but lifeguard attempts to restart it via handoff, the new master will sit waiting for a handoff and not take over normal operation. It can also overwrite the saved dump_restore buffers with nothing in the meantime.

[5a24e5c0|https://github.com/StreamMachine/StreamMachine/commit/5a24e5c0adb2493ca483c19f7f63591b2e831951] adds a timeout to handoff starts before falling back to normal start.

There currently isn't code to make sure no dump_restore buffers are written until we're fully started. That would be a good addition.

Lifeguard should also be fixed to not pass handoff after a crash.

**Comment by ewr** [comment]
Closing in favor of scpr/ops#7
